2020-05-13 20:34:04,536 - root - INFO - Started
2020-05-13 20:34:04,537 - root - ERROR - Traceback (most recent call last):
  File "train/train_wsi_on_512x1x1_pretrained.py", line 55, in <module>
    import_module(f'experiments_configs.{exp_subfolder}.{exp_name}')
  File "/home/ruslan/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ruslan/notebooks/pcancer/experiments_configs/wsi_on_dummy_512x1x1/90ep_sgd_exp_v1.py", line 1, in <module>
    import _default as d
ModuleNotFoundError: No module named '_default'

2020-05-13 20:35:13,862 - root - INFO - Started
2020-05-13 20:35:13,863 - root - ERROR - Traceback (most recent call last):
  File "train/train_wsi_on_512x1x1_pretrained.py", line 55, in <module>
    import_module(f'experiments_configs.{exp_subfolder}.{exp_name}')
  File "/home/ruslan/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ruslan/notebooks/pcancer/experiments_configs/wsi_on_dummy_512x1x1/90ep_sgd_exp_v1.py", line 1, in <module>
    import _default as d
ModuleNotFoundError: No module named '_default'

2020-05-13 20:35:40,649 - root - INFO - Started
2020-05-13 20:35:40,981 - root - ERROR - Traceback (most recent call last):
  File "train/train_wsi_on_512x1x1_pretrained.py", line 130, in <module>
    trainer = Trainer(logger, max_epochs=hparams['epochs'], gpus=gpus,
KeyError: 'epochs'

2020-05-13 20:36:17,018 - root - INFO - Started
2020-05-13 20:36:17,019 - root - ERROR - Traceback (most recent call last):
  File "train/train_wsi_on_512x1x1_pretrained.py", line 55, in <module>
    import_module(f'experiments_configs.{exp_subfolder}.{exp_name}')
  File "/home/ruslan/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ruslan/notebooks/pcancer/experiments_configs/wsi_on_dummy_512x1x1/90ep_sgd_exp_v1.py", line 9, in <module>
    'epochs': epochs,
NameError: name 'epochs' is not defined

2020-05-13 20:36:31,911 - root - INFO - Started
2020-05-13 21:30:12,783 - root - INFO - Finished
